### ISSUE TITLE
Schedule based backup as part of the Kahu Data protection Management

### ISSUE THREAD

**Issue by SrinivasChilveri** [soda-cdm/kahu#140]
****Issue/Feature Description:**

Currently the Kahu user(Application Admin)  has to create the backups manually. 
So here i am proposing a feature /requirement i.e. Schedule based backups, so the Kahu system schedules the backups from the user provided backup policy or schedule policy .

The Main Requirements are as follows

1) Kahu system will provide  the schedule based backups

2) currently hooks, resource filtering etc are tightly coupled with the backup & restore, so planning to abstract such resources which can be used across the system & especially Hooks are related to particular application or micro service so better to have separation from backup so its very easy to Enhance & Manage

So the below abstractions will be added to the data protection mgmt
   a) ResourceSet : which will identify the group of applications or related application which user want to take backup

   b) Hooks

   c)  Schedule Policy 

3) The Schedule service will takes the backups based on the application admin provided Backup Policy or Schedule Policy

4) The Schedule based Data Protection Management may need to the Job Management to create the schedule backups

5) User can use any backup copy to restore the same.

Please do find the below link which is running document related to this requirements ( WIP)

https://docs.google.com/document/d/11wOj1EGTveBMtD5IKipx8EGhc2bn99O3/edit#heading=h.gjdgxs

**Why this issue to fixed / feature is needed(give scenarios or use cases):

Schedule based backups, so user once create policy & binds the policy with the backup so user need not required to worry about the backups.

User can use backup copies to restore based on his requirement.

**How to reproduce, in case of a bug: NA

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)

**Comment by AmitRoushan** [comment]
@SrinivasChilveri, similar [issue](https://github.com/soda-cdm/documentation/issues/7) is getting tracked in [documentation repo](https://github.com/soda-cdm/documentation)

**Comment by SrinivasChilveri** [comment]
Closing the issue as its tracked by issue (https://github.com/soda-cdm/documentation/issues/7)
