### ISSUE TITLE
Controller with business logic which includes Part-2

### ISSUE THREAD

**Issue by PravinRanjan10** [soda-cdm/kahu#34]
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Controller with business logic which includes:
1. Content Collections:
  * Configs (sc, config, secret etc.)
     

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by AmitRoushan** [comment]
Current Backup API handler all filters requested in the issue.
Please reopen the issue if feel otherwise
