### ISSUE TITLE
Metadatalocation in backup should be a required parameter

### ISSUE THREAD

**Issue by sushanthakumar** [soda-cdm/kahu#50]
please add MetadataLocation as Required field. 

_Originally posted by @PravinRanjan10 in https://github.com/soda-cdm/kahu/pull/49#discussion_r905699155_

**Comment by PravinRanjan10** [comment]
1. Add Required validation for backupLocation
2. Add Required Validation for ProviderName in backupLocation

**Comment by PravinRanjan10** [comment]
@subi9

**Comment by subi9** [comment]
I will be working on this.

**Comment by sushanthakumar** [comment]
Validation has been added to check metadata parameter and its existence
