### ISSUE TITLE
Resource Contents are overwritten if name of resource is same for two namespace

### ISSUE THREAD

**Issue by PravinRanjan10** [soda-cdm/kahu#78]
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by sushanthakumar** [comment]
Fixed with [Release V1.0.0](https://github.com/soda-cdm/kahu/releases/tag/v1.0.0)
