### ISSUE TITLE
Display of namespace mapping in restore object

### ISSUE THREAD

**Issue by PravinRanjan10** [soda-cdm/kahu#79]
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by AmitRoushan** [comment]
With [V.1.0](https://github.com/soda-cdm/kahu/releases/tag/v0.1.0) RC Restore API manages namespace mapping. 
Please feel free to reopen the issue
